blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('user/posts/<str:username>', views.UserPostListView.as_view(), name='user_posts_page'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('post/new/', views.PostCreateView.as_view(), name='new'),
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name = 'password_reset'),
         
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name = 'password_reset_done'),
         
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name = 'password_reset_confirm'),
         
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Post
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.

# HOMEPAGE VIEW.
def home(request):
    context = {
        'posts': Post.objects.all(),
        'title': 'Home'
    }
    return render(request, 'blog/home.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_created']
    paginate_by = 3

    extra_context = {
        'title': 'Home'
    }

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/users_posts.html'
    paginate_by = 5
    context_object_name = 'posts'

    extra_context = {
        'title': 'User Posts'
    }

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_created')


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    print(model)
    extra_context = {
    'title': 'post'
    }

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/new_post.html'
    fields = ['title', 'content']
    extra_context = {
        'title': 'new'
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    extra_context = {
        'title': 'Update'
    }
    template_name = 'blog/new_post.html'
    fields = ['title', 'content']

    def test_func(self):
        post = self.get_object()

        # Check if the current user is the post writer.
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/are_you_sure.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()

        if self.request.user == post.author:
            return True
        return False

blog/templates/blog/are_you_sure.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom pb-3">Delete Post</legend>
                <h3>Are you sure you want to delete this post ?</h3>
                <a href="{% url 'blog:detail' object.id %}" class="btn btn-outline-secondary">Cancel</a>
                <button type="submit" class="btn btn-outline-danger">Yes, delete</button>
            </fieldset>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
    {% comment %} Including all the head links {% endcomment %}
    {% include "blog/template_parts/head.html" %}
<body>
    <div class="container">
        {% comment %} Including navbar {% endcomment %}
        {% include "blog/template_parts/navbar.html" %}
        <br>
        {% comment %} Inckuding navbar {% endcomment %}

        <div class="row">
            <div class="col-lg-3">
                {% comment %} Include Sidebar {% endcomment %}
                {% include "blog/template_parts/sidebar.html" %}
            </div>
            <div class="col-lg-9">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}

                {% if next %}
                         <div class="alert alert-danger">Login first</div>
                {% endif %}
                {% block content %}{% endblock content %}
            </div>
        </div>
    </div>

    {% comment %} Including all the javascript links {% endcomment %}
    {% include "blog/template_parts/javascripts.html" %}    
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block content %}
 <div class="card">
            <div class="card-header">
                {{ object.title }}
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-3 col-md-2">
                        <img src="{{ post.author.profile.image.url }}" alt="profile image" class="rounded-circle img-fluid">
                    </div>
                    <div class="col-9 col-md-10">
                        <p><small>Written by <a href="{% url 'blog:user_posts_page' object.author.username %}">{{ object.author }} </a> on {{ post.date_created | date:"F d, Y - H:i" }}</small></p>
                        <p class="card-text">{{ object.content }}</p>
                        {% if  user.is_authenticated and user == object.author %}
                             <a href="{% url 'blog:update' object.id %}" class="btn btn-success">Edit Post</a>
                             <a href="{% url 'blog:delete' object.id %}" class="btn btn-outline-danger">Delete Post</a>
                        {% endif %}
                    </div>
                </div>
                
            </div>
        </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <div class="card-header">
                {{ post.title }}
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-3 col-md-2">
                        <img src="{{ post.author.profile.image.url }}" alt="profile image" class="rounded-circle img-fluid">
                    </div>
                    <div class="col-9 col-md-10">
                        <p><small>Written by {{ post.author }} on {{ post.date_created | date:"F d, Y" }}</small></p>
                        <p class="card-text">{{ post.content }}</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
                
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock content %}

blog/templates/blog/new_post.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom pb-3">New Post</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/users_posts.html
{% extends "blog/base.html" %}

{% block content %}
<h1>All Posts By {{ view.kwargs.username }} ({{page_obj.paginator.count}})</h1> 
    {% for post in posts %}
        <div class="card">
            <div class="card-header">
                {{ post.title }}
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-3 col-md-2">
                        <img src="{{ post.author.profile.image.url }}" alt="profile image" class="rounded-circle img-fluid">
                    </div>
                    <div class="col-9 col-md-10">
                        <p><small>Written by {{ post.author }} on {{ post.date_created | date:"F d, Y" }}</small></p>
                        <p class="card-text">{{ post.content | truncatechars:80 }}</p>
                        <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Details</a>
                    </div>
                </div> 
            </div>
        </div>
        <br>
    {% endfor %}

    {% if is_paginated %}
        <div>
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Next</a>
        {% endif %}

        
        {% for num in page_obj.paginator.page_range %}

            {% if page_obj.number == num %}
                <a href="?page={{ num }}" class="btn btn-info mb-4">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}" class="btn btn-outline-info mb-4">{{ num }}</a>
            {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}
    </div>        
    {% endif %}
{% endblock content %}